sonar.projectKey=kawtar-elhamraoui_projet_devsecops
sonar.organization=kawtar-elhamraoui
sonar.projectName=Projet DevSecOps
sonar.sources=micro_app/src
sonar.tests=micro_app/tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.scm.disabled=true