env:
  contexts:
  - name: "Default Context"
    urls:
    - http://localhost:8000
    includePaths:
    - "http://localhost:8000.*"
    
jobs:
- parameters:
    failOnError: true
    failOnWarning: true
    progressToStdout: true
  type: "passiveScan-config"
  
- parameters:
    maxDuration: 5
    maxChildren: 10
  type: "spider"
  
- parameters:
    maxRuleDurationInMins: 10
    maxScanDurationInMins: 15
  type: "activeScan"