sonar.projectKey=projet_devsecops
sonar.projectName=Projet DevSecOps
sonar.projectVersion=1.0
sonar.sources=micro_app/src
sonar.tests=micro_app/tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11